#!/bin/sh

ROOT=/mnt/mmc0.1

detect mmc0

global linux.bootargs.base="console=ttymxc0,115200 rw panic=-1 quiet"

global bootm.image=$ROOT/boot/Image
global linux.bootargs.earlycon="earlycon=ec_imx6q,0x30860000,115200"
global bootm.appendroot=1
global bootm.root_dev=/dev/mmc0.1
