#!/bin/sh

global boot.default=mmc0.1
global linux.bootargs.base="console=ttymxc2,115200 rw panic=-1 quiet cpuidle.off=1"
global linux.bootargs.earlycon="earlycon=ec_imx6q,0x30880000,115200"
global bootm.appendroot=1
global bootm.root_dev=/dev/mmc0.1

if [ "$bootsource" != "serial" ]; then
	global autoboot_timeout=0
	exit 0
fi
global autoboot=abort

if [ test -f "/dev/mmc0.root" ]; then
	usbgadget -a -A "/dev/mmc0.root(root)" -b
else
	usbgadget -a -A "" -b
fi