#!/bin/sh

if [ "$bootsource" != "serial" ]; then
	global autoboot_timeout=0
	global boot.default=mmc
	exit 0
fi
global autoboot=abort

if [ test -f "/dev/mmc0.root" ]; then
	usbgadget -a -A "/dev/mmc0.root(root)" -b
else
	usbgadget -a -A "" -b
fi